apiVersion: v1
kind: Pod
metadata:
  name: multicontainer-pod
spec:
  containers:
  - name: container-one
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: container-two
    image: busybox
    command: ['sh', '-c', 'while true; do echo hello; sleep 10; done']

