kind: Pod
apiVersion: v1
metadata:
  name: nodelabels-selector
  labels:
    env: development
spec:
  containers:
    - name: node-selector-cont1
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Hello-lokeshkumar; sleep 5 ; done"]
  nodeSelector:
   hardware: t2-medium
