apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-replicaset
spec:
  replicas: 10 
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
