apiVersion: v1
kind: Pod
metadata:
  namespace: lokeshns1
  name: webapp1
  labels:
    app: webapp1-label
spec:
  containers:
  - name: webapp1
    image: ubuntu
    ports:
     - containerPort: 8080
  - name: webapp2
    image: nginx
    ports:
     - containerPort: 8081

